#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <time.h>
#include <string.h>

int main(int argc, char *argv[]) {
  int rank, size;

  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);

  int token; //value to be generated by each process
  int largest[2]; //array sized to hold largest even and odd values (index 0 = vp (even values), index[1] = pres (odd values))
  char tokenStr[5] = {0}; //to hold int conversion to str
  char rankStr[5] = {0}; //to hold int conversion to str
  char concatStr[20] = {0}; //will hold final array to convert back to int

  srand((unsigned)time(NULL) + rank*size); //seed rand rum generator

  if (rank != 0) {
      MPI_Recv(&largest, 2, MPI_INT, (rank - 1) % size, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
      //printf("Process %d received pres %d, and vp %d from process %d\n", rank, largest[1], largest[0], (rank - 1) % size);
      token = rand() % 91+9; //generates random positive number between 10 and 100? //print statement to debug
      //concatenate 1 to front and rank to back
      sprintf(tokenStr, "%d", token);
      sprintf(rankStr, "%d", rank);
      sprintf(concatStr, "%d", 1);

      strcat(concatStr, tokenStr);
      strcat(concatStr, rankStr);
      token = atoi(concatStr);
      //decide if vp canidate, or if pres canidate
      if(token%2 == 0) { //is even (aka a vp canidate)
        if (token > largest[0]){ //value generated is greater than current largest even (vp)
          largest[0] = token;
        }
      } else{ //is odd (pres canidate)
        if (token > largest[1]){ //value generated is greater than current largest odd (pres)
          largest[1] = token;
        }
      }

  } else { //process 0
    token = rand() % 91+9; //generates random positive number between 10 and 100
    //concatenate 1 to front and rank to back
    sprintf(tokenStr, "%d", token);
    sprintf(rankStr, "%d", rank);
    sprintf(concatStr, "%d", 1);

    strcat(concatStr, tokenStr);
    strcat(concatStr, rankStr);
    token = atoi(concatStr); //connvert to int

    //initialize largest array
    largest[0] = token; //guarenteed even (vp canidate) because rank 0
    largest[1] = 1;
  }

  MPI_Send(&largest, 2, MPI_INT, (rank + 1) % size, 0, MPI_COMM_WORLD);

  // Now process 0 can receive from the last process.
  if (rank == 0) {
      MPI_Recv(&largest, 2, MPI_INT, size - 1, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
      //printf("Process %d received pres %d, and vp %d from process %d \n", rank, largest[1], largest[0], size - 1); //print statement to debug
      if(token%2 == 0) { //is even (aka a vp canidate)
        if (token > largest[0]){ //value generated is greater than current largest even (vp)
          largest[0] = token;
        }
      } else{ //is odd (pres canidate)
        if (token > largest[1]){ //value generated is greater than current largest odd (pres)
          largest[1] = token;
        }
      }
      printf("Largest President = %d; Largest VP = %d\n", largest[1], largest[0]);
  }

MPI_Finalize();
return 0;
}
